### PR TITLE
support loading script asynchronously

### PR DESCRIPTION
**Pull request by afeld**
No reason to block the browser for it.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Attributes

### CODE REVIEW

**Comment by afeld** [comment]
...that I'm aware of?

**Comment by afeld** [comment]
Actually, I take that back; there would be a race condition with [the `DOMContentLoaded` event](https://github.com/digital-analytics-program/gov-wide-code/blob/84562c7332b4497074a7c58144bcceb0ba0b6dec/Universal-Federated-Analytics.js#L899) getting fired. I'll look into how to support this. TODO: investigate `document.readyState`.

**Comment by afeld** [comment]
Fixed the script to work when loaded `async`hronously.

Previously, the script would only set up the trackers after the `DOMContentLoaded` or `onreadystatechange`, but now they will be run even if the script is executed after those events have fired.

I also noticed that the script was inconsistent about when the events were being set up. The `onreadystatechange` listener was only checking for `readyState === 'complete'`, even though the document is still in the `interactive` state when `DOMContentLoaded` is fired. Changed to set up the trackers in either `readyState`.

The JS diff is a bit hard to understand...probably easiest to just look at the end of the files [before](https://github.com/digital-analytics-program/gov-wide-code/blob/master/Universal-Federated-Analytics.js) and [after](https://github.com/afeld/gov-wide-code/blob/patch-1/Universal-Federated-Analytics.js).

**Comment by konklone** [comment]
Here's a diff of the PR with whitespace diffs removed:
https://github.com/digital-analytics-program/gov-wide-code/pull/28/files?w=1

Also, https://github.com/digital-analytics-program/gov-wide-code/pull/27 will also add `async` to the `<script>` tag. However, @afeld's PR suggests that DAP uses code that wasn't expecting it -- and has fixed it to do so. Worth investigating.

**Comment by konklone** [comment]
In my opinion, this should be a priority for the DAP to fix, however e-Nor chooses to integrate @afeld's contribution into their work.

The lack of an `async` attribute was not as big of a problem when the only option for agencies was self-hosting, because if the agency's page loaded at all, loading another asset from the same domain was likely to be guaranteed and immediate.

Now that DAP is pushing central hosting, that guarantee isn't there. When visiting an agency site (e.g. `www.state.gov`) the call to DAP's JavaScript will mean establishing a new connection to a third party domain (`dap.digitalgov.gov`). While DAP is hosted using a CDN that offers global performance and availability, establishing a connection to a new server is an unavoidable delay. Additionally, for a user with a not-great internet connection (which is many people), all new connections might introduce delay, regardless of how performant the server is.

Because of this, without an `async` tag, agencies's websites may halt loading and rendering until the DAP code has been downloaded. If the DAP's `<script>` tag is the last thing in an agency's HTML, that impact may be minimal, but I have seen agencies include the `<script>` in their header, which could create a noticeable problem.

I haven't personally verified @afeld's bug or the fix, but this is something e-Nor should do. Again, while the diff in this PR looks extensive, [this diff with whitespace changes removed is simpler](https://github.com/digital-analytics-program/gov-wide-code/pull/28/files?w=1).

Unfortunately, because this involves a change to the recommended `<script>` tag itself, and not just a change to the JavaScript code, it will be necessary to go ask agencies to individually update their `<script>` tag. Because of this, it would be helpful to address this bug and update the recommended `<script>` tag before engaging in wide-scale publicizing of the new central hosting location.

**Comment by jalan** [comment]
The [official instructions](http://www.digitalgov.gov/services/dap/analytics-tool-instructions/) for using this project now recommend both using the central hosting location and putting the script in `<head>`. Please give us `async` or at least change the recommendation.

**Comment by konklone** [comment]
@jalan Where does it say to put the script in `<head>`?

I agree that we should not recommend it go in `<head>` while `async` is not supported.

**Comment by jalan** [comment]
@konklone Oh, sorry, it's not on the webpage itself, but in the full instructions in the [linked PDF](https://www.digitalgov.gov/files/2014/05/QuickGuide-Sept-2015.pdf):

> Insert the Federated Analytics script block in the \<head\> of all pages on your site.

**Comment by monfresh** [comment]
Any updates on this issue?

**Comment by tdlowden** [comment]
Hey @monfresh, this feature is included in our upcoming version 3.1 release, which we were just about to pull the trigger on, but we identified a bug. Hope to have it fixed and have the version rolled out by the end of the month.

**Comment by monfresh** [comment]
Great! Thanks @tdlowden.

**Comment by tdlowden** [comment]
Finally available as of today in v3.1! Closing.

**Pull request closed without merging**
